### ISSUE TITLE
Modify to work with  eFolder Service Version 1

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/connect_vbms#125]
The VBMS team is upgrading to a new service called eFolder Service Version 1. They will be deprecating the old service in UAT in March and we should update connect_vbms to work with the new service.

Get in touch with @shanear, for more details on the API docs (in his email) and some of the potential gotchas with the new API.

**Comment by amprokop** [comment]
A few thoughts for discussion, posted in separate comments:

1. one approach might be to just add the new VBMS services (they have different names now, `ListDocuments` will now be `FindDocumentSeriesReference` for example) to the connect-vbms gem without changing the old connect-vbms API, and then just change caseflow & efolder to use the new VBMS services when we’re satisfied that everything works correctly.

For example:

```  
def self.fetch_documents_for(appeal)
    @vbms_client ||= init_vbms_client

    sanitized_id = appeal.sanitized_vbms_id

    if (ENV['USE_VBMS_V5'])
      request = VBMS::Requests::FindDocumentSeriesReference.new(sanitized_id)
    else
      request = VBMS::Requests::ListDocuments.new(sanitized_id)
    end

    documents = send_and_log_request(sanitized_id, request)

    appeal.documents = documents.map do |vbms_document|
      Document.from_vbms_document(vbms_document)
    end

    appeal
  end
```

but also, there is an argument for i can just changing it under the hood and making it opaque to the applications — *if* we don’t need any new inputs or anything like that, which we should make sure of.

**Comment by amprokop** [comment]
Item #2: Do we want to change the VBMS signature in any way when we implement this, for instance to remove the constructor (e.g. `VBMS::Requests::FindDocumentSeriesReference` instead of ``VBMS::Requests::FindDocumentSeriesReference.new`) ? @shanear brought this up for the reason that connect-vbms doesn't work like other ruby gems.

**Comment by amprokop** [comment]
@aroltsch @shanear, can you weigh in on this topic? Any other input from others would be great too.

**Comment by amprokop** [comment]
@aroltsch has done great work on this so far and I'm going to follow in her footsteps.

**Comment by aroltsch** [comment]
[Release 12.0 VBMS eFolder Service v1.0 SCD.pdf](https://github.com/department-of-veterans-affairs/connect_vbms/files/810904/Release.12.0.VBMS.eFolder.Service.v1.0.SCD.pdf)

**Comment by aroltsch** [comment]
@amprokop I like your idea of using `USE_VBMS_V5` environmental variable to switch between two versions. We will have to change how eFolder express handles the responses because the responses will be different with a new service.

**Comment by amprokop** [comment]
got it, @aroltsch, thanks for the update!!!

**Comment by aroltsch** [comment]
Issues to follow up:
1. Use MTOM when uploading and downloading files (issue created with VBMS team: https://github.com/department-of-veterans-affairs/dsva-vbms/issues/74
2. examName and newMail parameters are no longer supported when uploading documents (need to confirm this with the team)
3. Documentation needs to be updated

**Comment by kierachell** [comment]
Uploading Works.

<img width="1170" alt="screen shot 2017-03-17 at 8 55 35 pm" src="https://cloud.githubusercontent.com/assets/18075411/24067506/3e480c70-0b54-11e7-8578-10c8a8dce662.png">
<img width="1411" alt="screen shot 2017-03-17 at 8 56 26 pm" src="https://cloud.githubusercontent.com/assets/18075411/24067507/3e622f74-0b54-11e7-803d-366c326a151c.png">
uploading large files does not work.

Without documentation I cannot make a clear assessment as to what `work with the new service` means.

**Comment by kierachell** [comment]
listing documents: old vs new
<img width="1420" alt="screen shot 2017-03-17 at 9 26 16 pm" src="https://cloud.githubusercontent.com/assets/18075411/24067870/6f7f437c-0b58-11e7-88f2-dc007ca19851.png">

**Comment by kierachell** [comment]
Ok, then let's do this hardcore:
<img width="849" alt="screen shot 2017-03-17 at 9 48 13 pm" src="https://cloud.githubusercontent.com/assets/18075411/24068052/f0dda622-0b5b-11e7-812e-63b46bb458af.png">
<img width="1421" alt="screen shot 2017-03-17 at 9 50 28 pm" src="https://cloud.githubusercontent.com/assets/18075411/24068054/f0e02276-0b5b-11e7-9a7b-ed3b99c4f1b5.png">
<img width="1415" alt="screen shot 2017-03-17 at 9 51 35 pm" src="https://cloud.githubusercontent.com/assets/18075411/24068053/f0e03630-0b5b-11e7-8682-f03e220dfae7.png">

**Comment by kierachell** [comment]
<img width="756" alt="screen shot 2017-03-17 at 9 58 15 pm" src="https://cloud.githubusercontent.com/assets/18075411/24068091/ddb8a208-0b5c-11e7-8015-068029a96842.png">
<img width="1385" alt="screen shot 2017-03-17 at 9 58 19 pm" src="https://cloud.githubusercontent.com/assets/18075411/24068090/ddb6ea08-0b5c-11e7-86d9-986ef983789f.png">

At least they're equally off.

**Note** list documents is _much_ faster

**Comment by kierachell** [comment]
EstablishClaim still works

**Comment by kierachell** [comment]
Downloading large documents (46mb) is not working currently:
 - for ID: 149092082
```
down_req = VBMS::Requests::GetDocumentContent.new("{32F14E19-2D78-4E9A-A07C-F764CC6BA0DF}")
#<VBMS::Requests::GetDocumentContent:0x007ffbde44d428 @document_id="{32F14E19-2D78-4E9A-A07C-F764CC6BA0DF}">
down_res = client.send_request(down_req)
VBMS::SOAPError: Unable to parse SOAP message
```

- for ID 149092081
```
#<VBMS::Requests::GetDocumentContent:0x007ffbe383fba8 @document_id="{9A9F584A-DB12-4F86-9CF0-355258352516}">
VBMS::SOAPError: Unable to parse SOAP message
```

**Comment by amprokop** [comment]
:(

**Comment by kierachell** [comment]
Ok, more on the `restricted` field:
```
#<VBMS::Requests::FindDocumentSeriesReference:0x007ffbe4186c98 @file_number="561349914">
[27] pry(main)> ref_res = client.send_request(ref_req)
=> [#<OpenStruct document_id="{0DE52299-33D3-439C-8F6A-AA46E98F848F}", type_description="VA 9 Appeal to Board of Appeals", type_id="179", doc_type="179", subject=nil, received_at=Sat, 05 Sep 2015, source="VACOLS", mime_type="application/pdf", alt_doc_types=nil, restricted=nil>,
 #<OpenStruct document_id="{B2BA7614-DFA5-430C-BEBC-F4622CC91DEF}", type_description="Notice of Disagreement", type_id="73", doc_type="73", subject=nil, received_at=Tue, 01 Sep 2015, source="VACOLS", mime_type="application/pdf", alt_doc_types=nil, restricted=nil>,
 #<OpenStruct document_id="{C095DC2F-B1A4-439C-9306-EF3A13E4D9B5}", type_description="Statement of Case (SOC)", type_id="95", doc_type="95", subject=nil, received_at=Thu, 03 Sep 2015, source="VACOLS", mime_type="application/pdf", alt_doc_types=nil, restricted=nil>,
 #<OpenStruct document_id="{00BC9050-0000-C210-AFAA-6A936CAEC5A7}", type_description="VA 8 Certification of Appeal", type_id="178", doc_type="178", subject="Form 8", received_at=Thu, 22 Oct 2015, source="VACOLS", mime_type="application/pdf", alt_doc_types=nil, restricted=nil>]
[28] pry(main)> ref_req = VBMS::Requests::FindDocumentSeriesReference.new("561349914")
=> #<VBMS::Requests::FindDocumentSeriesReference:0x007ffbdc7982d8 @file_number="561349914">
[29] pry(main)> ref_res = client.send_request(ref_req)
=> [#<OpenStruct document_id="{0DE52299-33D3-439C-8F6A-AA46E98F848F}", type_description="VA 9 Appeal to Board of Appeals", type_id="179", doc_type="179", subject=nil, received_at=Sat, 05 Sep 2015, source="VACOLS", mime_type="application/pdf", alt_doc_types=nil, restricted=false>,
 #<OpenStruct document_id="{B2BA7614-DFA5-430C-BEBC-F4622CC91DEF}", type_description="Notice of Disagreement", type_id="73", doc_type="73", subject=nil, received_at=Tue, 01 Sep 2015, source="VACOLS", mime_type="application/pdf", alt_doc_types=nil, restricted=false>,
 #<OpenStruct document_id="{C095DC2F-B1A4-439C-9306-EF3A13E4D9B5}", type_description="Statement of Case (SOC)", type_id="95", doc_type="95", subject=nil, received_at=Thu, 03 Sep 2015, source="VACOLS", mime_type="application/pdf", alt_doc_types=nil, restricted=false>,
 #<OpenStruct document_id="{00BC9050-0000-C210-AFAA-6A936CAEC5A7}", type_description="VA 8 Certification of Appeal", type_id="178", doc_type="178", subject="Form 8", received_at=Thu, 22 Oct 2015, source="VACOLS", mime_type="application/pdf", alt_doc_types=nil, restricted=false>]
```

Sending a request the first time returns `nil` for restricted values; 2nd request (same ID) returns `false`.

lolwut?

**Comment by kierachell** [comment]
At this point it is unclear whether the discrepancies are due to VBMS bugs, `connect_vbms` bugs, "feature-bugs" and if I am even supposed to validate these things.

**Comment by aroltsch** [comment]
## Test case 2: 320102183
Documents that are missing from FindDocumentSeriesReference:
```["{E0E91416-C9CA-44B4-A1C9-0E13F98817CE}", "{77EA9539-EE54-40D5-8805-680B721FD01F}", "{EC0707A9-6D34-43F0-BD4E-DAC1E8EDA275}"]```
These are older versions for this document: {1191573C-7EB8-4E40-9DB8-7C36529F929A}.
We have decided that for FindDocumentSeriesReference, we will only display the latest version. 

Here is the entire output:
![image](https://cloud.githubusercontent.com/assets/3811786/24165589/2a809c02-0e47-11e7-8df4-c276a63c730f.png)

**Comment by aroltsch** [comment]
## Test case 4: 561349920
https://github.com/department-of-veterans-affairs/connect_vbms/issues/140

**Comment by aroltsch** [comment]
## Test case 1: 110301139

### Benchmark 
Benchmark is better with implementation of a new Multipart Parser https://github.com/department-of-veterans-affairs/connect_vbms/pull/139
```
request = VBMS::Requests::FindDocumentSeriesReference.new("110301139")
1.080000   0.130000   1.210000 ( 13.870670)
request = VBMS::Requests::ListDocuments.new("110301139")
0.180000   0.050000   0.230000 (  6.453750)
```
However, still 7 seconds difference

### FindDocumentSeriesReference vs ListDocuments count
If I compare document IDs for both requests, there are 74 document ID that don't match
```doc_series_response.map(&:document_id) - list_doc_res.map(&:document_id)
=> 74
````

**Comment by aroltsch** [comment]
## Test case 3: 796147498

### FindDocumentSeriesReference vs ListDocuments count
If I compare document IDs for both requests, there are 494 document ID that don't match
```
doc_series_response.map(&:document_id) - list_doc_res.map(&:document_id)
=> 494
```

**Comment by aroltsch** [comment]
## Test Case 7: 796017172

### FindDocumentSeriesReference vs ListDocuments count
If I compare document IDs for both requests, there are 386 document ID that don't match

### GetDocumentContent for {D03E944F-0000-CA1D-8A0B-266A6792A264}
works with MTOM https://github.com/department-of-veterans-affairs/connect_vbms/pull/139

**Comment by kierachell** [comment]
So it seems like he have a few issues generated from this:
- VBMS has some issues?
- What type/kind/version of documents are we to display for eFolder
- How is this gem connected to eFolder?

I presume this will be the master issue for those and will be blocked until then.

**Comment by kierachell** [comment]
Response from the VBMS team:
>“Document types of “C&P EXAM XML” (type_id 999981) are not visible on the VBMS UI EFolder. This is intended behavior for this one document type and it is the only document type that does not show on the eFolder but will appear in the Edoc and eFolder API calls. There are 324 documents of this type in the database for filenumber 110301139 which explains the discrepancy that you are seeing for that filenumber.

```(ref_res.map(&:doc_type) - [“999981”]).count => 329```

`[#<VBMS::Responses::DocumentType:0x007fef191d3d90 @description="C&P Exam", @type_id="356">]` and `[#<VBMS::Responses::DocumentType:0x007fef191c1758 @description="C&P Exam XML", @type_id="999981">]`

So that does explain part of the problem.

**Comment by kierachell** [comment]
## Restricted Value Testing: 

behavior seems to have changed - some documents have the field set to `nil` and other `false` (as opposed to per-request)

folder number:117533875
```
[23] pry(main)> ref_req = VBMS::Requests::FindDocumentSeriesReference.new("117533875")
=> #<VBMS::Requests::FindDocumentSeriesReference:0x007fe874cdd048 @file_number="117533875">
[24] pry(main)> ref_res = client.send_request(ref_req)
=> [#<OpenStruct document_id="{9AE4C378-7BB4-4F91-BF56-6F94F095808A}", type_description="Third Party Correspondence", type_id="475", doc_type="475", subject=nil, received_at=Fri, 03 Jun 2016, source="VBMS", mime_type="application/pdf", alt_doc_types=nil, restricted=nil>,
 #<OpenStruct document_id="{CD63D5A3-2C90-4654-8EF0-AD7ECE5252D3}", type_description="Correspondence", type_id="34", doc_type="34", subject=nil, received_at=Fri, 03 Jun 2016, source="VBMS", mime_type="application/pdf", alt_doc_types=nil, restricted=nil>,
 #<OpenStruct document_id="{4B3662CF-CD85-4E71-A7FA-8AB86F4B3C16}", type_description="DPRIS - DD 214 Certified Original - Certificate of Release or Discharge From Active Duty", type_id="488", doc_type="488", subject=nil, received_at=Thu, 02 Jun 2016, source="VBMS", mime_type="application/pdf", alt_doc_types=nil, restricted=false>,
 #<OpenStruct document_id="{8B3E0CB0-A988-4D3A-9F3E-A11EB112850D}", type_description="Power of Attorney (incl. VA 21-22, VA 22a)", type_id="85", doc_type="85", subject=nil, received_at=Thu, 02 Jun 2016, source="VBMS", mime_type="application/pdf", alt_doc_types=nil, restricted=false>,
 #<OpenStruct document_id="{5E216839-5C76-4613-8E48-435B1CB2D6D7}", type_description="VA 21-526 Veterans Application for Compensation or Pension", type_id="131", doc_type="131", subject=nil, received_at=Thu, 02 Jun 2016, source="VBMS", mime_type="application/pdf", alt_doc_types=["Appeals - Supplemental Statement of the Case (SSOC)"], restricted=false>,
 #<OpenStruct document_id="{C77F590D-E826-4A6A-9645-FD5BE20923CB}", type_description="VA 21-4138 Statement In Support of Claim", type_id="115", doc_type="115", subject=nil, received_at=Thu, 02 Jun 2016, source="VBMS", mime_type="application/pdf", alt_doc_types=["Appeals - Notice of Disagreement (NOD)"], restricted=false>,
 #<OpenStruct document_id="{893448BE-C895-40AF-80ED-D21FEC130D05}", type_description="VA 21-4142a General Release for Medical Provider Information", type_id="827", doc_type="827", subject=nil, received_at=Thu, 02 Jun 2016, source="VBMS", mime_type="application/pdf", alt_doc_types=nil, restricted=false>,
 #<OpenStruct document_id="{1261C7AC-5F25-460F-9B5A-CB328ED638C0}", type_description="DPRIS - DD 214 Certified Original - Certificate of Release or Discharge From Active Duty", type_id="488", doc_type="488", subject="eFolder Express", received_at=Thu, 02 Jun 2016, source="VBMS", mime_type="application/pdf", alt_doc_types=nil, restricted=false>]
```
