### ISSUE TITLE
README says this uses Java

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/connect_vbms#130]
@shanear I thought you pulled all the Java out?  Is the encryption code still using Java or is the README just a little behind?

**Comment by shanear** [comment]
The Java is used for testing it.

For our high level tests we:
1) encrypt in Java, then decrypt in ruby
2) encrypt in ruby, then decrypt in java

**Comment by ayaleloehr** [comment]
Roger. Closing then. thank you for the quick clarification!
