### ISSUE TITLE
SPIKE | Verify that we can read the "Subject" property under "Editable Properties" using the VBMS API

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/connect_vbms#136]
We're considering introducing a custom code that ROs will use to label certain types of documents in eFolder (specifically, form 119, used to report contact with a Veteran). We need to check if the "Subject" under "Editable Properties" in VBMS is accessible in the ListDocuments call (or equivalent). It's important that the document list call exposes this property to us and not the actial document fetch, otherwise we would have to potentially fetch every document to check if a particular document is present.

Steps to verify would be:
- Modify an eFolder in the VBMS UAT UI to give it "TEST123" for this "Subject" property
- Manually call the VBMS document list service, and inspect the results to determine if "TEST123" is readable anywhere.
- Post the code used to find it here to give the developer working on this integration a leg up later :)

![image](https://cloud.githubusercontent.com/assets/3781835/23993957/1ed9b564-0a19-11e7-8136-7e02918f4f8d.png)

**Comment by amprokop** [comment]
@aroltsch or @shanear might also know the answer to this offhand.

**Comment by aroltsch** [comment]
eFolder Service Version 1.0 findDocumentSeriesReference (listDocuments in older version) returns subject in the response. We need to add subject to the response in FindDocumentSeriesReference
```<ns2:versions documentSeriesRefId="{95FD13DE-5ADD-488F-BF45-50C0993AEE34}" documentVersionRefId="{5B8D57C5-270F-4BFC-9A3B-1235EB5EF62F}" mimeType="application/pdf" subject="Knee">```

**Comment by amprokop** [comment]
great. closing this.
