### ISSUE TITLE
Use MTOM for GetDocumentContent service

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/connect_vbms#137]
https://github.com/department-of-veterans-affairs/dsva-vbms/issues/74

**Comment by aroltsch** [comment]
Testing:
I have implemented a new HTTP parser with this ticket. We need to re-test all services:
Old Services:
FetchDocumentById
UploadDocumentWithAssociations
ListDocuments
GetDocumentTypes

New Services:
FindDocumentSeriesReference
GetDocumentContent
InitializeUpload/UploadDocument

**Comment by kierachell** [comment]
## TEST CASE UPLOAD:
- File #: 561349920
- 20MB PDF = OK
- 50MB PDF take 1 = Not OK: `VBMS::SOAPError: Unable to parse SOAP message`
- 50MB PDF take 2 = Not OK: `VBMS::SOAPError: Unable to parse SOAP message`

## TEST CASE DOCUMENT CONTENT 1:
- File #: 796017172
- Document ID: `{D03E944F-0000-CA1D-8A0B-266A6792A264}`
- Size: 58MB
- WORKS!

## TEST CASE DOCUMENT CONTENT 2:
- File #: 320102183
- Document ID: `{57F136A2-8F75-4904-8FD7-556965EF05EB}`
- Size: 60MB
- WORKS-ish - file is corrupted and doesn't show on VBMS anyway

## TEST CASE DOCUMENT CONTENT 3:
- File #: 796017172
- Document ID: `{D03E944F-0000-CA1D-8A0B-266A6792A264}` and `{90F1934F-0000-C917-A976-512D2F6C95BC}`
- Size: 58ish MB
- WORKS!

**Comment by kierachell** [comment]
**PASSED**
Well, I was supposed to just validate the Download which worked.
