### ISSUE TITLE
Leverage approriate client to avoid unnecessary handshakes when making repeat HTTP requests

### ISSUE THREAD

**Issue by amoose** [department-of-veterans-affairs/connect_vbms#14]
Issue:

When making multiple HTTP requests to the same host, we want to avoid new TCP connections and TLS handshakes for subsequent requests.

> Is `HTTPI` the best HTTP lib to use if I want to make many requests to the same host?
> The way it's API is structured leads me to believe that htat means a new TCP conncetion, a new TLS session, for each request.
> Which would be cruddy.
> Is there an HTTP API which is good?

**Comment by alex** [comment]
While I was asking those questions about a different project, it would be great to have a given `VBMS::Client` reuse HTTP sessions where possible.

In Python I'd just attach a `requests.Session` to the `Client` and let it handle the connection reuse automatically. Hopefully there's a similarly good ruby approach that we can take.

One note on this: whatever we do we should make sure to document the concurrency implications thereof.

**Comment by llimllib** [comment]
I think we would automatically avoid new TCP connections if we set it up so that HTTPI was calling [httpclient](http://www.rubydoc.info/gems/httpclient/2.1.5.2/HTTPClient):

> What does HTTPClient do?  Well, every time you use a connection, HTTPClient will (thread-safely) examine it’s existing cached connections (for any host, not just the one you are about to make a request to), and clean up (properly closing their sockets) any that haven’t been used since a timeout value (by default 15 seconds, the same as what apache will timeout a persistent connection).

- [source](https://bibwild.wordpress.com/2012/04/30/httpclient-is-a-nice-http-client-forin-ruby/)

in the end, we probably ought to ditch the HTTPI layer, but this could work for now?

**Comment by alex** [comment]
that sounds reasonable to me

On Thu, Aug 20, 2015 at 7:42 PM, Bill Mill <notifications@github.com> wrote:

> I think we would automatically avoid new TCP connections if we set it up
> so that HTTPI was calling httpclient
> <http://www.rubydoc.info/gems/httpclient/2.1.5.2/HTTPClient>:
>
> What does HTTPClient do? Well, every time you use a connection, HTTPClient
> will (thread-safely) examine it’s existing cached connections (for any
> host, not just the one you are about to make a request to), and clean up
> (properly closing their sockets) any that haven’t been used since a timeout
> value (by default 15 seconds, the same as what apache will timeout a
> persistent connection).
>
>
>    - source
>    <https://bibwild.wordpress.com/2012/04/30/httpclient-is-a-nice-http-client-forin-ruby/>
>
> in the end, we probably ought to ditch the HTTPI layer, but this could
> work for now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/connect_vbms/issues/14#issuecomment-133212227>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by harrisj** [comment]
One thing to note, if you want to mock HTTP requests and are using `HTTPclient`, you need to use [webmock](https://github.com/bblimke/webmock) and not the Fakeweb gem

**Comment by harrisj** [comment]
Okay, looking at the code for HTTPI, and it does do this if you're using the httpclient adapter

```ruby
def initialize(request)
  @request = request
  @client = ::HTTPClient.new
end
```

I think it will then use this client for all requests. It does reinit the SSL config, but it might just reuse the connections. What's weird is that HTTPi has some mechanisms for setting things like cert_password and http_client doesn't have (but the SSL object is passed directly to httpclient so it seems to work)

**Comment by harrisj** [comment]
Did the PR #22 actually make a difference in this regard?

**Comment by alex** [comment]
I spent some time reviewing `HTTPI` and `HTTPClient` source code, my answer is that unfortunately it probably doesn't work. I think the correct solution is to just use `HTTPClient` directly, so we can ensure that we only have a single `HTTPClient` instance per `VBMS::Client`.
