### ISSUE TITLE
Implement MTOM for UploadDocument for documents greater than 50MB

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/connect_vbms#140]
From VBMS eFolder Service v1 documentation: VBMS eDocument and eFolder services do not enforce a document size limitation; however, document size has a dramatic impact on end user experience for VA personnel and external users. Systems uploading documents should attempt to keep documents as small as possible to reduce negative impact to both system resources and end users. For eDocument service and eFolder Inline uploads, 50MB files and below are recommended. Documents above 50MB have a higher chance to fail during these service operations. 100MB files and below are recommended for eFolder MTOM upload operations. VBMS may incorporate file size validations in a future to enforce these recommendations.

**Comment by aroltsch** [comment]
It was decided to put MTOM implementation on hold for UploadDocument service because we only upload small documents as of right now so we can use eFolder Inline uploads (no MTOM)

**Comment by alisan16** [comment]
This hasn't been updated in over 2 years. Closing.
