### ISSUE TITLE
Add JRuby 9k to travis CI

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/connect_vbms#15]

**Comment by amoose** [comment]
I have tested jruby-9.0.0.0 locally, but RVM is currently behind the jruby release and only installs pre1 in Travis (which causes errors). I will push up the new .travis.yml once the RVM version is released and updated in Travis CI. 

More info:
- https://github.com/rvm/rvm/issues/3475

**Comment by alex** [comment]
Good to know, thanks.

On Sat, Aug 22, 2015 at 12:45 PM, Amos Stone <notifications@github.com>
wrote:

> I have tested jruby-9.0.0.0 locally, but RVM is currently behind the jruby
> release and only installs pre1 in Travis (which causes errors). I will push
> up the new .travis.yml once the RVM version is released and updated in
> Travis CI.
>
> More info:
>
>    - rvm/rvm#3475 <https://github.com/rvm/rvm/issues/3475>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/connect_vbms/issues/15#issuecomment-133725457>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by amoose** [comment]
blocked until RVM is released and available in Travis CI.

**Comment by jodosha** [comment]
Ouch :broken_heart:

**Comment by amoose** [comment]
@jodosha For now, I added a quick hack to install rvm from master. 
- https://github.com/department-of-veterans-affairs/connect_vbms/blob/44af05841998ad5707db28135d215f2ac069148b/.travis.yml#L29-L37

**Comment by alex** [comment]
Done!
