### ISSUE TITLE
ListDocuments vs FindDocumentSeriesReference count discrepancies

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/connect_vbms#154]
NSD ticket has been filed VBMS PROD Ticket I14769991FY17 Document Issue
on May 31, 2017

URL to search for NSD ticket (use Safari): http://vaww.sdm21127.nsd.va.gov/CAisd/pdmweb8.exe

We encountered a document count difference between the eDocument Service v4 ListDocuments and the eFolder Service 1.0 FindDocumentSeriesReference in Production environment. 

The file number: [Anya has it]. 

When we call ListDocuments for the above file number, we receive 508 documents which matches with what we see in the VBMS UI. However,
when we call FindDocumentSeriesReference we receive 200 documents. In FindDocumentSeriesReference response, there are a few documents that have multiple document versions. One document with the documentSeriesRefId {17897442-06F5-4C2F-BE87-D8FEBE9FC34E} has 309 different versions. We searched though all the versions for this document and there were 50 different document type ids. It appears to us that this document with the documentSeriesRefId {17897442-06F5-4C2F-BE87-D8FEBE9FC34E} might contain 309 different documents but is treated as one by the FindDocumentSeriesReference API. 

We then looked at a few more file numbers and found more count differences. Here are a few examples:
[Anya has it]

**Comment by aroltsch** [comment]
Response from the VBMS dev team: 
```the Dev team has discovered it is a data issue and they are currently working to resolve it```

**Comment by aroltsch** [comment]
Email sent from Nicholas on 06/26/2017

**Comment by aroltsch** [comment]
Date: Monday, June 26, 2017 at 3:21 PM
```Nicholas,
     I updated the defect with this information and the dev team will look at it.  It might take a day or two to get back to you so please be patient.```

**Comment by aroltsch** [comment]
Date: Wednesday, July 12, 2017

```
I’m trying to sort that out.  We are about to deploy another patch for a separate issue that EVSS had with the eFolder services so that has taken precedence since Monday morning.  As soon as I have resources available to work with you on the counts issue, I will get back to you.
```

**Comment by aroltsch** [comment]
This is done.
