### ISSUE TITLE
Add retry attempt to all VBMS requests on SSL error

### ISSUE THREAD

**Issue by joofsh** [department-of-veterans-affairs/connect_vbms#156]
SSL errors are causing ~.1% of requests to VBMS to fail. It is unclear the timeline for VBMS to fix this. In the meantime, we should add a 1 attempt retry to all our VBMS requests.

Related sentry errors:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/391/
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/376/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/409/

**Comment by joofsh** [comment]
Haven't seen an SSL error in 24 hours. Closing this issue

**Comment by mmlumba** [comment]
More related SSL issues: 
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow-certification/issues/368/
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/436/
