### ISSUE TITLE
Gem should support clients who want to connect to backend services through a sidecar proxy

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/connect_vbms#162]
## AC

If the connect-vbms client is initialized by a client like so:
```
    VBMS::Client.from_env_vars(
      logger: VBMSCaseflowLogger.new,
      env_name: ENV["CONNECT_VBMS_ENV"],
      use_proxy: true
    )
```
If `ENV["PROXY_BASE_URL"]` is set, instead of sending requests to `env_name: ENV["CONNECT_VBMS_ENV"]`, requests will be sent to `ENV["PROXY_BASE_URL"]/route` with `Host: env_name: ENV["CONNECT_VBMS_ENV"]` passed as a header

**Comment by kierachell** [comment]
1. This might need to be a feature toggle of some sort (maybe based on an envvar?)
   - Considering that every `VBMS_ENV` is appended with `vba.va.gov` - would it be simpler to just change the var to have the whole hostname? Consider https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/ansible/vars/va-service.yml
   - This way we can just toggle it from `url` to `localhost` or to even an internal IP (if we ever decide to make it a remote proxy)
1. You can also remove the `https` from the requests
1. The basic idea here is to make this more modular to allow developers to be able to use this locally as well:
   - You will be able to point `connect_vbms` to a `localhost:port` and use ssh port forwarding through the jumpbox to use real VBMS;

**Comment by amprokop** [comment]
`1. This might need to be a feature toggle of some sort (maybe based on an envvar?)`

Yes, but the feature toggle should be implemented by the client, not in this gem— so in Caseflow/Efolder, you would have:

```
   VBMS::Client.from_env_vars(
      logger: VBMSCaseflowLogger.new,
      env_name: ENV["CONNECT_VBMS_ENV"],
      sidecar_proxy_port: FeatureToggle.enabled?(:envoy) ? 10001 : nil
    )
```

**Comment by amprokop** [comment]
```

**Comment by askldjd** [comment]
Done
