### ISSUE TITLE
Add removeContention request

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/connect_vbms#190]
We have the need to remove contentions when editing the issues on an AMA review. This will require adding a request to call the `removeContention` endpoint.

The documentation for this endpoint is attached:
[VBMS Claim Services Version 4.0 Service Contract Document (Revision 5.0).docx](https://github.com/department-of-veterans-affairs/connect_vbms/files/2202636/VBMS.Claim.Services.Version.4.0.Service.Contract.Document.Revision.5.0.docx)

**Comment by leikkisa** [comment]
This document is awesome

**Comment by leikkisa** [comment]
I'm putting blocked on this because there's something wrong with the XML, and hoping to get an example of what it should look like from VBMS (or perhaps help from someone experienced with adding operations).

**Comment by leikkisa** [comment]
I got an example request from Joe, now I am asking him about what to use for all of the required fields (there are a number that I don't understand).

**Comment by leikkisa** [comment]
I validated this with VBMS UAT on file_number: 984562385, claim: 600132141, contention: 303202
It doesn't exist anymore, but it said "Happy Tuesday."
