### ISSUE TITLE
Make open timeout small

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/connect_vbms#218]
Typically, open (or connect) timeouts should be very small. If we can't connect to the server in a few seconds, it's often not worth it to wait 600 seconds. We recently had the same issue in the BGS client, and we reduced it to 10 seconds: https://github.com/department-of-veterans-affairs/ruby-bgs/pull/77/files

We should do the same here: https://github.com/department-of-veterans-affairs/ruby-bgs/pull/77/files

**Comment by monfresh** [comment]
cc @pkarman

**Comment by pkarman** [comment]
Agreed!

**Comment by alisan16** [comment]
Closing this unless it is found to actively cause issues
