### ISSUE TITLE
Add to Gemnasium

### ISSUE THREAD

**Issue by harrisj** [department-of-veterans-affairs/connect_vbms#23]
[Gemnasium](gemnasium.com) is a service for alerting developers when their projects are using old gems and if any gems have active security vulnerabilities. It is free for public and open source projects. We should enable it for connect_vbms.

**Comment by llimllib** [comment]
I started to do it, but I don't have permission

**Comment by alex** [comment]
@llimllib what permission were you missing?

**Comment by llimllib** [comment]
Not entirely clear to me, but this is the screen I end up on:

![authorize_gemnasium](https://cloud.githubusercontent.com/assets/7150/9537012/42c9ae92-4d01-11e5-87ba-023c85137333.png)

I wasn't sure enough what to do, so I didn't click "Request access"

**Comment by alex** [comment]
Hit "request access", that'll bug me to approve the application.

On Thu, Aug 27, 2015 at 9:19 PM, Bill Mill <notifications@github.com> wrote:

> Not entirely clear to me, but this is the screen I end up on:
>
> [image: authorize_gemnasium]
> <https://cloud.githubusercontent.com/assets/7150/9537012/42c9ae92-4d01-11e5-87ba-023c85137333.png>
>
> I wasn't sure enough what to do, so I didn't click "Request access"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/connect_vbms/issues/23#issuecomment-135597123>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by llimllib** [comment]
OK, done

**Comment by llimllib** [comment]
https://gemnasium.com/department-of-veterans-affairs/connect_vbms
