### ISSUE TITLE
Regexps are being used to parse HTML

### ISSUE THREAD

**Issue by harrisj** [department-of-veterans-affairs/connect_vbms#24]
For instance, [here in the client.rb code](https://github.com/department-of-veterans-affairs/connect_vbms/blob/master/src/vbms/client.rb#L135). We should fix to just parse whole document in Nokogiri (maybe can check that response is proper content type)

**Comment by harrisj** [comment]
Fixed in #45

**Comment by harrisj** [comment]
This can be closed now

**Comment by amoose** [comment]
Completed with #52
