### ISSUE TITLE
Split requests.rb into multiple files

### ISSUE THREAD

**Issue by harrisj** [department-of-veterans-affairs/connect_vbms#25]
I want to split the requests.rb file into a separate file for each class because I'm sure that rubocop will make noises and I feel like it's another thing to clean up now that the dust has settled.

**Comment by llimllib** [comment]
:+1:... this could probably be a part of #13 (which is languishing a bit)

**Comment by harrisj** [comment]
Do you want me to review #13 and merge in?

**Comment by llimllib** [comment]
it's not ready for merge, but if you could review it and make sure that the nokogiri stuff seems equivalent to the erb, and that the tests are adequate, I'll delete the erb methods so it's ready for a final review and merge.

**Comment by alex** [comment]
This happened.
