### ISSUE TITLE
More unit tests for requests

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/connect_vbms#26]
Right now most of the tests of the requests go through integration, it'd be great to start with getting unit tests on the response parsing as seen here: https://github.com/department-of-veterans-affairs/connect_vbms/blob/master/spec/list_documents_spec.rb

**Comment by llimllib** [comment]
#13, which still needs review, adds a bit too, with one like this for each requests class: https://github.com/department-of-veterans-affairs/connect_vbms/blob/remove-erb-xml/spec/get_document_types_request_spec.rb
