### ISSUE TITLE
Minor Aesthetic Tweaks

### ISSUE THREAD

**Issue by harrisj** [department-of-veterans-affairs/connect_vbms#29]
Now that others have bravely pioneered the path and got it working, I'm just here to do some minor cleanup in their wake. Just a few other things I want to do, noting them here in one place:

- [X] Change constructor of client.rb to take an options hash instead (punting on this for now)
- [x] ~~Add methods to `client.rb` to create a message type and call send~~ (nixed by Alex)
- [x] `# TODO: this can't really be correct` in `client#build_request` (fixed by @llimllib)
- [x] Make `VBMS::Document` into real Ruby object with method to construct from XML tree (PR #58)
- [x] Rename `Client#send` to have a name that doesn't shadow `Object#send` (PR #71)

Probably a few other things to add here and below in comment, but this is a start for my notes. This is *not* a critique of prior code.

**Comment by llimllib** [comment]
probably rename `send` so it isn't shadowing `Object#send`

**Comment by llimllib** [comment]
Also I'm pretty sure that `this can't really be correct` is in fact correct; what it says is that when connecting to the test server (`@key` is only nil in test), we don't want to do SSL verification. Although it's possible we could figure out the cert to do so I guess? Though it seems a bit unnecessary to me.

**Comment by alex** [comment]
@llimllib I believe you're correct about that.

**Comment by alex** [comment]
I'd actually prefer we _dont_ add methods to `client.rb`, I think the approach of just creating objects and executing them, it makes it much easier to write code which uses `connect_vbms` easy to test.

**Comment by amoose** [comment]
Nice work, @harrisj
