### ISSUE TITLE
Use pure Ruby for encryption and remove Java

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/connect_vbms#5]
We should be able to do all the crypto stuff with just ruby.

<hr>

Use ruby for encryption and decryption.
- [x] Verify structure in SOAP envelope
  - [ ] add specs to validate SOAP structure
- [x] Sign appropriate nodes (envelope and document) depending on type and timestamp
- [ ] Permit encryption algorithm to be dynamic (SHA1? pshaww!)

**Comment by awong-dev** [comment]
We're really close in the SoapScum bits.  I just hadn't finished figuring out how to correctly invoke the dsig api.
