### ISSUE TITLE
The tests run too slowly

### ISSUE THREAD

**Issue by llimllib** [department-of-veterans-affairs/connect_vbms#56]
We have such a small test suite, it should run more quickly. Figure out how.

**Comment by harrisj** [comment]
One issue might be the webmocks. Currently these encrypt the XML messages on the fly before setting the webmock to return them for requests. We should make sure this encryption is only done once before all tests in a suite rather than before each test

**Comment by harrisj** [comment]
Before many of the tests we encrypt the SOAP response first and then decrypt it in the test. Unsurprisingly, this seems to be the issue with the tests running slowly as reported by `rspec -p`

```
Top 10 slowest examples (27.42 seconds, 99.7% of total time):
  VBMS::Requests FetchDocumentById executes succesfully when pointed at VBMS
    6.6 seconds ./spec/requests/requests_spec.rb:56
  VBMS::Requests ListDocuments executes succesfully when pointed at VBMS
    3.99 seconds ./spec/requests/requests_spec.rb:47
  VBMS::Requests GetDocumentTypes executes succesfully when pointed at VBMS
    3.66 seconds ./spec/requests/requests_spec.rb:71
  VBMS::Requests UploadDocumentWithAssociations executes succesfully when pointed at VBMS
    3.06 seconds ./spec/requests/requests_spec.rb:21
  Ruby Encrypt/Decrypt test vs Java reference impl handles roundtripping utf-8 content.
    2.64 seconds ./spec/ruby_crypto_spec.rb:52
  Ruby Encrypt/Decrypt test vs Java reference impl encrypts in ruby, and decrypts using java
    2.13 seconds ./spec/ruby_crypto_spec.rb:13
  VBMS::Client from_env_vars process_response when it is given valid encrypted XML should return a decrypted XML document
    1.96 seconds ./spec/client_spec.rb:179
  VBMS::Client from_env_vars process_response when it is given a document that won't decrypt should raise a SOAPError
    1.89 seconds ./spec/client_spec.rb:212
  Ruby Encrypt/Decrypt test vs Java reference impl encrypts in java, and decrypts using ruby
    1.37 seconds ./spec/ruby_crypto_spec.rb:32
  VBMS::Client multipart_boundary should extract the boundary from the header
    0.10757 seconds ./spec/client_spec.rb:73
```

Noted that the entire test suite takes approximately 60 seconds on my machine. Of course, on Travis, we are running it for 6 different environments (JDK and Ruby combinations), so that means at least 4 minutes or so on the CI server. We can eliminate half of these environments when we no longer use Java to encrypt in the gem, but I don't see any serious ways to fix this unless we wanted to pre-encrypt the test documents (which would mean also using Timecop to fix tests to run at the time of the signing)

**Comment by llimllib** [comment]
Right now, we invoke java on the command line to encrypt and decrypt; meaning we incur a warmup cost each time, which I'll wager is most of the cost of encrypting/decrypting. One way to speed it up would be to investigate ways to keep java process running between tests.

(I have no idea if this is feasible with a reasonable amount of work, or would require spending a disproportionate amount of time messing with the Java code. I somewhat suspect it's the latter, but I just wanted to mention the possibility)

**Comment by harrisj** [comment]
That is a good point. I'm not sure how to do this easily except if we ran the Java process as some sort of RPC receiver and already I'm worried it's getting complicated, but I don't know enough about Java to say

**Comment by alex** [comment]
Yeah, I think putting calories into a persistent Java process would not be
a good use of those calories as excising the Java.

On Thu, Sep 17, 2015 at 9:55 PM, Jacob Harris <notifications@github.com>
wrote:

> That is a good point. I'm not sure how to do this easily except if we ran
> the Java process as some sort of RPC receiver and already I'm worried it's
> getting complicated, but I don't know enough about Java to say
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/connect_vbms/issues/56#issuecomment-141305944>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by llimllib** [comment]
These tools look like they might persist a JVM process and let us run without a startup cost:

* drip: https://github.com/flatland/drip
* nailgun: http://www.martiansoftware.com/nailgun/

I'm looking into it in my free time? Not clear to me why but it's satisfying to me at the moment.

**Comment by harrisj** [comment]
You've changed, Bill. This place has gotten to you if you are looking into
Java tools in your spare time.

(let me know what you find)

**Comment by llimllib** [comment]
I got both installed; drip didn't seem to speed anything up and failed when inserted into the tests for reasons that are unclear to me. nailgun worked and speeded things up for the first invocation of the encryption program, but then the program crashed on subsequent runs.

I was unable to find any java parameters with significant effect on the execution time.

In case anybody else wants to try, here's how I started nailgun:

```bash
    CLASSPATH=/Users/llimllib/adhoc/connect_vbms/classes:/Users/llimllib/adhoc/connect_vbms/lib/*:/Users/llimllib/adhoc/connect_vbms/lib:/Users/llimllib/adhoc/connect_vbms/src/main/properties:/usr/local/Cellar/nailgun/0.9.1/libexec/nailgun-server-0.9.1.jar \
    java \
    -Dlogfilename=/Users/llimllib/adhoc/connect_vbms/log/upload.log \
    com.martiansoftware.nailgun.NGServer
```

and you can then run `EncryptSOAPDocument` with:

`ng EncryptSOAPDocument /Users/llimllib/adhoc/connect_vbms/spec/fixtures/requests/upload_document_with_associations.xml /Users/llimllib/adhoc/connect_vbms/spec/fixtures/test_keystore.jks importkey uploadDocumentWithAssociationsResponse`

(Adjust the paths for your own computer, obviously)

**Comment by shanear** [comment]
This doesn't seem to be a problem anymore. closing.
