### ISSUE TITLE
Fix time issue with received_date?

### ISSUE THREAD

**Issue by harrisj** [department-of-veterans-affairs/connect_vbms#62]
In `UploadDocumentWithAssociations` there is this code that converts to local date. I think depending on time of year, this might have issues when EDT is only 4 hours off of GMT? Or will it be okay since it just shifts to 1am locally and not 12am?

```
def received_date
  @received_at.getlocal('-05:00').strftime('%Y-%m-%d-05:00')
end
```

**Comment by alex** [comment]
FWIW, this was a detail obtained through much sadnes  by @llimllib and @greggersh. While it may be bizzare, I don't think it's wrong. Probably is due a comment though.

**Comment by amoose** [comment]
Good eye, Jacob. The verdict was to leave as is, but let's add a comment inline so it doesn't trip up new devs.

**Comment by harrisj** [comment]
Okay, I will add a comment in a PR. Just to confirm, the VBMS system is asking/returning dates for documents as datetimes, but it really only uses them for the date, right?

**Comment by amoose** [comment]
Completed with #69
