### ISSUE TITLE
Are there other eDocumentService v4 methods we need to support?

### ISSUE THREAD

**Issue by harrisj** [department-of-veterans-affairs/connect_vbms#70]
No rush; just noting this in an issue so we won't forget about it

**Comment by alex** [comment]
(Thanks for filing an issue for this!)

**Comment by llimllib** [comment]
I'm not sure I follow, the endpoint is set by `CONNECT_VBMS_URL`?

**Comment by harrisj** [comment]
Ooops, I apologize for the confusion. Bill is correct that because this is
SOAP, there is only a single Endpoint that we send all our requests to
unlike the more sane world of REST with different endpoints for different
purposes. I mean to say are there other SOAP methods we should be able to
query.

**Comment by llimllib** [comment]
ah, OK makes sense now. CUI doesn't need access to any more is all I know for sure.

**Comment by harrisj** [comment]
There doesn't seem to be a need for anything right now, so closing this issue
