### ISSUE TITLE
to_h methods on DocumentType and Document

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/connect_vbms#76]
When they were `Struct` objects, `DocumentType` and `Document` had `to_h` methods, and now they don't. These should be brought back I think.

**Comment by llimllib** [comment]
Which also means that df8be89 should have been a major version change

**Comment by harrisj** [comment]
Fair enough, but if people are just pulling from git head anyway... (do we think we want to move to having a separate development branch?)

**Comment by llimllib** [comment]
we don't pull from head in CUI, we use it as a gem

**Comment by amoose** [comment]
Completed with #78
