### ISSUE TITLE
Document the logger option

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/connect_vbms#77]

**Comment by amoose** [comment]
This looks great except for our strong opinion to avoid a standard Ruby logger. I would prefer to default to a standard Ruby-type logger. Am I missing something?

**Comment by alex** [comment]
The reason I wrote this interface was to ensure we could pass around
structured data, AFAIK the Ruby logger just deals in strings.

On Fri, Oct 2, 2015 at 10:19 AM, Amos Stone <notifications@github.com>
wrote:

> This looks great except for our strong opinion to avoid a standard Ruby
> logger. I would prefer to default to a standard Ruby-type logger. Am I
> missing something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/connect_vbms/issues/77#issuecomment-145034338>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by harrisj** [comment]
Yeah, I guess if you wanted we could define some sort of basic logger within VBMS that is just a wrapper around the Ruby logger

```ruby
class VBMS::DebugLogger
  def log(event, data)
    case event
    when :unencrypted_xml
       Logger.debug("Unencrypted XML: #{data[:unencrypted_body]}"
      # and so on
     end
  end
end
```

Then people could use that to print out debug logging if they needed to. What do you think? I would be inclined against making it a default parameter to `client#initialize` because it's a bit of a security issue if you deploy that to production, but people could use it explicitly when testing things out locally.

**Comment by alex** [comment]
I think the API is fine as-is, if we find comon ground in the loggers are
different users need, we can evaluate including them in connect_vbms then.

On Fri, Oct 2, 2015 at 10:54 AM, Jacob Harris <notifications@github.com>
wrote:

> Yeah, I guess if you wanted we could define some sort of basic logger
> within VBMS that is just a wrapper around the Ruby logger
>
> class VBMS::DebugLogger
>   def log(event, data)
>     case event
>     when :unencrypted_xml
>        Logger.debug("Unencrypted XML: #{data[:unencrypted_body]}"
>       # and so on
>      end
>   endend
>
> Then people could use that to print out debug logging if they needed to.
> What do you think? I would be inclined against making it a default
> parameter to client#initialize because it's a bit of a security issue if
> you deploy that to production, but people could use it explicitly when
> testing things out locally.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/connect_vbms/issues/77#issuecomment-145050272>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by amoose** [comment]
Roger that Alex, minimal API changes :+1:
