### ISSUE TITLE
Stop using erbs to render xml

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/connect_vbms#8]

**Comment by llimllib** [comment]
Rather do it all through Nokogiri? Because you're worried about generating invalid XML? How come?

**Comment by alex** [comment]
invalid XML is a lower level concern, consistent and guarnteed escaping is more pressing

independent of this we could do with some reduced-copy-paste of the soap XML elements

**Comment by harrisj** [comment]
Escaping is indeed an important concern, and it would be preferable to even use XML::Builder.

Furthermore, it might make more sense to explore one of the recent Ruby SOAP libraries:

* [Handsoap](https://github.com/unwire/handsoap/) (works with httpclient)
* [Savon](http://savonrb.com/version2/client.html)

These could generate valid SOAP requests and possibly even help with signing and encryption headers. There is also a lovingly named gem named lolsoap, but that one requires the remote endpoint to have WSDL.

**Comment by llimllib** [comment]
my first approach was with savon, if I never see that library again I'll be happy :)

anyway, I implemented it with XML::Builder in #13, sorry I didn't previously link it to this issue. It's super simple and dragging in a soap library is probably overkill, I think?

**Comment by harrisj** [comment]
Fair enough and I see it now. Good call!

Sent from my iPhone

On Aug 21, 2015, at 7:45 PM, Bill Mill <notifications@github.com> wrote:

my first approach was with savon, if I never see that library again I'll be
happy :)

anyway, I implemented it with XML::Builder in #13
<https://github.com/department-of-veterans-affairs/connect_vbms/pull/13>,
sorry I didn't previously link it to this issue. It's super simple and
dragging in a soap library is probably overkill, I think?

—
Reply to this email directly or view it on GitHub
<https://github.com/department-of-veterans-affairs/connect_vbms/issues/8#issuecomment-133591705>
.
