### ISSUE TITLE
Formalize a Git branching methodology

### ISSUE THREAD

**Issue by harrisj** [department-of-veterans-affairs/connect_vbms#80]
As we move toward a more stable version of this gem, we need to formalize a process for contributing to the gem's code without breaking applications that are using it. I would like to propose that we officially adopt [git flow](http://nvie.com/posts/a-successful-git-branching-model/) and merge in pull requests to a separate `develop` branch instead of master. Then we can use master for merging from develop and updating the version of the gem when we are ready for new releases.

**Comment by harrisj** [comment]
It seems like Git Flow has been rejected. Are there any other workflows you're prefer for branching/merging and updating the gem version?

**Comment by alex** [comment]
I think we should go with:

- Make your own branch, send a PR.
- `master` should be stable, don't land things with failing tests or regressions.
- when we decide there's a significant milestone, bump the version and tag it.

**Comment by harrisj** [comment]
That's fine, but I'm concerned about avoiding a repeat of the issue that happened when we merged PR #58. None of the tests failed, but it broke applications using the code because they relied on some methods in Ruby's `Struct` that were not in the refactored class definitions. In hindsight, we should've also upped the version, but I guess the flow would be to do that with a commit to master right after PRs are merged, right? I suppose in addition, we need to look at the test coverage and beef that up.

**Comment by alex** [comment]
Would we have caught the issue earlier under a git-flow workflow, or would
doing a release simply have caused the same breakage?

On Wed, Oct 14, 2015 at 2:49 PM, Jacob Harris <notifications@github.com>
wrote:

> That's fine, but I'm concerned about avoiding a repeat of the issue that
> happened when we merged PR #58
> <https://github.com/department-of-veterans-affairs/connect_vbms/pull/58>.
> None of the tests failed, but it broke applications using the code because
> they relied on some methods in Ruby's Struct that were not in the
> refactored class definitions. In hindsight, we should've also upped the
> version, but I guess the flow would be to do that with a commit to master
> right after PRs are merged, right? I suppose in addition, we need to look
> at the test coverage and beef that up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/department-of-veterans-affairs/connect_vbms/issues/80#issuecomment-148154372>
> .
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by harrisj** [comment]
No, the release would've caused the same breakage, but as part of the release process we would've probably bumped the gem version up, making it easier to avoid it with setting the Gemfile version. Also, it would've probably shown up for apps using the edge that pull the gem directly from git and the `develop` branch.

One other thing we could try is to keep master where stuff is merged into, but make sure we do a better job of tagging master.
