### ISSUE TITLE
Scan CUI and caseflow for connect VBMS methods

### ISSUE THREAD

**Issue by amoose** [department-of-veterans-affairs/connect_vbms#85]
The goals:
- [x] Ensure we are not removing (or planning to) remove any used methods in the API. 
- [ ] Ensure pessimistic versioning (twiddle-wakka ~>) or another mechanism is in place to keep breaking changes from entering these repos.
  - [caseflow](https://github.com/department-of-veterans-affairs/caseflow/blob/master/Gemfile#L33) currently has the gem vendored but, let's also add proper versioning. 
  - [CUI](https://github.com/adhocteam/DrTurbotax/blob/master/Gemfile#L29) aka DrTurboTax
  - [efolder-express](https://github.com/department-of-veterans-affairs/efolder-express/blob/master/config/test.yml#L9-L11) has no versioning whatsoever

**Comment by llimllib** [comment]
CUI uses the logger, `VBMS::Client.from_env_vars`, `VBMS::Requests::UploadDocumentWithAssociations.new`, and `client.send`. The interface is very small.

**Comment by amoose** [comment]
Thanks, Bill!

**Comment by alex** [comment]
efolder-express also uses `connect_vbms`

**Comment by amoose** [comment]
Thx, included both in issue checklist.

**Comment by harrisj** [comment]
Notes from looking at Caseflow:
1. Initializer sets a `$vbms` global with call to `VBMS::Client.from_env_vars`
2. Uses a `VBMS::Requests::ListDocuments` request to get a list of documents
    a. Expect to be able to call `to_i` on `Document.doc_id`
    b. Expects to be able to call `beginning_of_day` on `Document.received_at`
3. Uses `VBMS::Requests::UploadDocumentWithAssociations` to upload new documents

It's using a vendored gem that is version 0.0.2 of the connect_vbms gem for now. I think it should work if updated to latest gem, but will look that those methods on the Document model work first.

**Comment by harrisj** [comment]
Notes from looking at CUI:
- Has a dedicated VBMS job class running that initializes with `VBMS::Client.from_env_vars`
- Passes a logger into the VBMS initializer
- Sends up document with `VBMS::Requests::UploadDocumentWithAssociations.new`
- Returns the resulting doc from the UploadDocumentWithAssociations from the DelayedJob's `perform` method, but I don't think this is stored/used anywhere (DJ only cares about exceptions)
- Checks for following exceptions on the request send, logs and rethrows
   - VBMS::HTTPError
   - VBMS::ExecutionError
   - VBMS::ClientError
   - StandardError

It's using version 0.0.2 of the `connect_vbms` gem via an explicit set in the Gemfile

**Comment by harrisj** [comment]
Efolder-express is a Python script. Is it using the Ruby gem at all?

**Comment by amoose** [comment]
efolder-express does use the VBMS gem here:
- https://github.com/department-of-veterans-affairs/efolder-express/blob/master/efolder_express/vbms.py

**Comment by llimllib** [comment]
python writing a ruby file, executing it with bash, running ruby, executing java with bash. Beautiful :heart_eyes:

**Comment by harrisj** [comment]
Does Github have support for the Inception horn sound effect?

**Comment by harrisj** [comment]
Notes from looking at efolder-express:
- Builds a Ruby file as a string via a Python script, then runs it via the shell
- Runs against a locally checked-out repo of the gem (although could be switched to use Ruby gems)
- Use the `VBMS::Client.new` constructor (set with values supplied by Env Vars to Twisted?)
- It seems to be using the `to_h` method of the Document class for rendering out reply.

**Comment by harrisj** [comment]
I think we are good on complying with all this being used currently (ie, the first checkbox). The second part is really up to the maintainers of these projects.

**Comment by shanear** [comment]
This seems not relevant anymore. Closing
