### ISSUE TITLE
Proposed cleanups for the SoapScum module

### ISSUE THREAD

**Issue by harrisj** [department-of-veterans-affairs/connect_vbms#94]
Now that the bulk of Ruby encryption/decryption work has been done, I want to clean up a few things. As always, this isn't a judgment on any of the excellent and difficult coding required to make this work. I'm just here to do this sort of thing:
- [ ] We probably should rename the `SoapScum` module to something more boring and predictable. Perhaps `VBMS::SOAP`
- [x] The `SoapScum::XMLNamespaces` declaration is redundant with some XML namespace declarations elsewhere in the code. We should replace with just one
- [ ] Move the Keystore class to a separate file. Define some tests.
- [x] Make the SecureRandom.hex() use a slightly longer sequence to make collisions even less likely. ~~Should we have some sort of ID registry to make them impossible (imagining how impossible it would be to debug an occasional error from the same ID being used twice in a document)~~ No need for a registry

I will add more tweaks here and link to relevant PRs off the checkboxes.

**Comment by alex** [comment]
All sound fine to me, but no ID registry, the odds are vanishingly small and the odds of a bug in that code are way more likely.
