### ISSUE TITLE
Fix mistake in logging docs

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/connect_vbms#96]
In the `request` docs, it says that the `:request` key is an `HTTPI::Request`, actually it's an instance of whatever `request` type was passed to `send_request`, not the internal `HTTPI` one

**Comment by paultag** [comment]
Ah, beat me to the bug, was about to file this

**Comment by harrisj** [comment]
Oops, I guess this is my mistake. Thank you for the fix.
